FROM node:22-alpine

WORKDIR /app
RUN apk add --no-cache \
  python3 \
  make \
  g++ \
  libc6-compat
RUN corepack enable
ARG DATABASE_URL
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json turbo.json ./
COPY ./packages ./packages


COPY ./apps/ws ./apps/ws

RUN pnpm install 


RUN pnpm run build

CMD ["pnpm", "--filter", "web", "run", "dev"]

